env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g grunt-cli

sudo: false

after_script:
  - grunt coveralls

language: node_js
node_js:
  - "4"
  - "5"
  - "stable"
